language: python

python:
  - "3.6"

install:

  - pip install -r requirements.txt
  - pip install codecov coveralls
    


script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
  - codecov --token=c854cf5c-b5f1-401a-98cc-6bedb183f1bf